### ISSUE TITLE
32-bit Build?

### ISSUE THREAD

**Issue by Epictyphlosion** [atsb/ReBOOM#2]
Since there's a build for DOS now, I think it's only logical that there be a build for 32-bit machines, preferably with XP and 2000 compatibility.

**Comment by atsb** [comment]
XP and 2000 compatibility is impossible due to the use of SDL2 libraries (which do not guarantee support for those operating systems).  I can do a 32bit build but it would be for Windows 8 and higher.

**Comment by Epictyphlosion** [comment]
> I can do a 32bit build but it would be for Windows 8 and higher.

According to an SDL wiki page, this isn't the case: http://wiki.libsdl.org/Installation 

"Win32 and Win64 are both supported, and we support any Windows version back to Windows XP."

**Comment by atsb** [comment]
While this is true, I compile my own SDL2 libraries from source code.  Those are built without XP support since I build them on Windows 11 using the Windows SDK which does not have the XP SDK.
